// Generate unique.h via cbindgen when the `ffi` feature is enabled.
//
// The header is written to the crate root (so it shows up in the repo).
// On other platforms or without the feature, this is a no-op.

#[cfg(feature = "ffi")]
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_file = std::path::Path::new(&crate_dir).join("unique.h");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("UNIQUE_H".to_string()),
        autogen_warning: Some(
            "/* Warning: this file is auto-generated by cbindgen. Do not edit. */".to_string(),
        ),
        ..Default::default()
    };

    match cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file(&output_file);
            println!("cargo:warning=Generated C header: {}", output_file.display());
        }
        Err(e) => {
            println!("cargo:warning=cbindgen failed: {e}");
        }
    }
}

#[cfg(not(feature = "ffi"))]
fn main() {}
