#ifndef KUNGFU_H
#define KUNGFU_H

/* Warning: this file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum number of header pairs stored inline (on the stack).
 * Beyond this, SmallVec falls back to the heap transparently.
 */
#define INLINE_HEADER_CAPACITY 16

/**
 * An incoming HTTP request.
 */
typedef struct Request Request;

/**
 * A response that handlers build up and the server flushes to the wire.
 */
typedef struct Response Response;

/**
 * The top-level router. Owns the trie plus the registered middleware chain.
 */
typedef struct Router Router;

typedef struct Server Server;

/**
 * Opaque router handle.
 */
typedef struct Router KungfuRouter;

/**
 * Opaque server handle.
 */
typedef struct Server KungfuServer;

/**
 * Opaque request handle. The C side receives this as a pointer and passes
 * it to the helper functions (`kungfu_request_param`, etc.) to extract data.
 */
typedef struct Request KungfuRequest;

/**
 * Opaque response handle.
 */
typedef struct Response KungfuResponse;

/**
 * Create a new router. Returns an opaque pointer that the caller owns.
 * Free with `kungfu_router_free`.
 */
KungfuRouter *kungfu_router_new(void);

/**
 * Free a router created by `kungfu_router_new`.
 *
 * # Safety
 * The pointer must have been returned by `kungfu_router_new` and not
 * already freed.
 */
void kungfu_router_free(KungfuRouter *router);

/**
 * Create a new server bound to a router. Returns an opaque pointer.
 * The server takes ownership of the router.
 */
KungfuServer *kungfu_server_new(KungfuRouter *router);

/**
 * Free a server created by `kungfu_server_new`.
 */
void kungfu_server_free(KungfuServer *server);

/**
 * Start the server listening on the given port. Blocks the calling thread.
 *
 * Note: this function blocks forever. The C caller should run it in a
 * dedicated thread if it needs to do other work.
 */
void kungfu_server_listen(KungfuServer *server, int port);

/**
 * Get a route parameter by name. Returns a null-terminated string, or NULL
 * if the parameter doesn't exist.
 */
const char *kungfu_request_param(const KungfuRequest *req, const char *key);

/**
 * Get a request header by name. Returns NULL if not present.
 */
const char *kungfu_request_header(const KungfuRequest *req, const char *key);

/**
 * Get the request body as a pointer + length.
 */
const uint8_t *kungfu_request_body(const KungfuRequest *req, unsigned int *len);

/**
 * Set the response status code.
 */
void kungfu_response_status(KungfuResponse *res, int code);

/**
 * Set a response header.
 */
void kungfu_response_header(KungfuResponse *res, const char *key, const char *value);

/**
 * Set the response body from raw bytes.
 */
void kungfu_response_body(KungfuResponse *res, const uint8_t *data, unsigned int len);

/**
 * Set the response body from a JSON string. Also sets content-type.
 */
void kungfu_response_json(KungfuResponse *res, const char *json);

/**
 * Set an error response.
 */
void kungfu_response_error(KungfuResponse *res, int code, const char *message);

#endif  /* KUNGFU_H */
