#ifndef UNIQUE_H
#define UNIQUE_H

/* Warning: this file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum number of header pairs stored inline (on the stack).
 * Beyond this, SmallVec falls back to the heap transparently.
 */
#define INLINE_HEADER_CAPACITY 16

/**
 * An incoming HTTP request.
 */
typedef struct Request Request;

/**
 * A response that handlers build up and the server flushes to the wire.
 */
typedef struct Response Response;

/**
 * The top-level router. Owns the trie plus the registered middleware chain.
 */
typedef struct Router Router;

typedef struct Server Server;

/**
 * Opaque router handle.
 */
typedef struct Router UniqueRouter;

/**
 * Opaque server handle.
 */
typedef struct Server UniqueServer;

/**
 * Opaque request handle. The C side receives this as a pointer and passes
 * it to the helper functions (`unique_request_param`, etc.) to extract data.
 */
typedef struct Request UniqueRequest;

/**
 * Opaque response handle.
 */
typedef struct Response UniqueResponse;

/**
 * Create a new router. Returns an opaque pointer that the caller owns.
 * Free with `unique_router_free`.
 */
UniqueRouter *unique_router_new(void);

/**
 * Free a router created by `unique_router_new`.
 *
 * # Safety
 * The pointer must have been returned by `unique_router_new` and not
 * already freed.
 */
void unique_router_free(UniqueRouter *router);

/**
 * Create a new server bound to a router. Returns an opaque pointer.
 * The server takes ownership of the router.
 */
UniqueServer *unique_server_new(UniqueRouter *router);

/**
 * Free a server created by `unique_server_new`.
 */
void unique_server_free(UniqueServer *server);

/**
 * Start the server listening on the given port. Blocks the calling thread.
 *
 * Note: this function blocks forever. The C caller should run it in a
 * dedicated thread if it needs to do other work.
 */
void unique_server_listen(UniqueServer *server, int port);

/**
 * Get a route parameter by name. Returns a null-terminated string, or NULL
 * if the parameter doesn't exist.
 */
const char *unique_request_param(const UniqueRequest *req, const char *key);

/**
 * Get a request header by name. Returns NULL if not present.
 */
const char *unique_request_header(const UniqueRequest *req, const char *key);

/**
 * Get the request body as a pointer + length.
 */
const uint8_t *unique_request_body(const UniqueRequest *req, unsigned int *len);

/**
 * Set the response status code.
 */
void unique_response_status(UniqueResponse *res, int code);

/**
 * Set a response header.
 */
void unique_response_header(UniqueResponse *res, const char *key, const char *value);

/**
 * Set the response body from raw bytes.
 */
void unique_response_body(UniqueResponse *res, const uint8_t *data, unsigned int len);

/**
 * Set the response body from a JSON string. Also sets content-type.
 */
void unique_response_json(UniqueResponse *res, const char *json);

/**
 * Set an error response.
 */
void unique_response_error(UniqueResponse *res, int code, const char *message);

#endif  /* UNIQUE_H */
