/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsRequest {
  requestId: number
  method: string
  path: string
  query: string
  params: string
  headers: string
  body: string
}
export interface JsResponse {
  status: number
  body: string
}
export declare function compileCss(classes: string): string
export declare function compileCssDir(dir: string): string
export declare function version(): string
export declare class KungfuApp {
  constructor()
  get(path: string, handler: (arg: string) => any): Promise<void>
  post(path: string, handler: (arg: string) => any): Promise<void>
  put(path: string, handler: (arg: string) => any): Promise<void>
  delete(path: string, handler: (arg: string) => any): Promise<void>
  /** Called from JS to send a response back to Rust for a pending request. */
  respond(requestId: number, response: JsResponse): Promise<void>
  listen(port: number): Promise<void>
}
