//! TypeScript type generation from route metadata.
//!
//! Walks the Kungfu router's registered routes and produces a
//! `routes.d.ts` file with typed wrappers. The frontend gets full
//! autocomplete when calling backend routes, similar to tRPC.

use kungfu_core::router::RouteMeta;
use kungfu_core::Method;

/// A simplified type spec for a single route, used to generate TS types.
#[derive(Debug, Clone)]
pub struct RouteTypeSpec {
    pub path: String,
    pub method: Method,
    pub params: Vec<(String, String)>, // (name, TS type)
    pub request_type: Option<String>,
    pub response_type: Option<String>,
}

/// Generate a TypeScript declaration file from route metadata.
///
/// Output looks like:
/// ```typescript
/// // Auto-generated by kungfu generate types. Do not edit.
/// declare namespace KungfuRoutes {
///   interface GetUserById {
///     path: '/users/:id';
///     method: 'GET';
///     params: { id: string };
///     response: { id: number; email: string };
///   }
///   // ...
/// }
/// ```
pub fn generate_typescript(routes: &[RouteMeta]) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str("// Auto-generated by `kungfu generate types`. Do not edit.\n");
    out.push_str("declare namespace KungfuRoutes {\n");

    for meta in routes {
        let spec = route_meta_to_spec(meta);
        let interface_name = derive_interface_name(&spec);
        out.push_str(&format!("  interface {} {{\n", interface_name));
        out.push_str(&format!("    path: '{}';\n", spec.path));
        out.push_str(&format!("    method: '{}';\n", spec.method.as_str()));

        if spec.params.is_empty() {
            out.push_str("    params: {};\n");
        } else {
            out.push_str("    params: {\n");
            for (name, ty) in &spec.params {
                out.push_str(&format!("      {}: {};\n", name, ty));
            }
            out.push_str("    };\n");
        }

        if let Some(req) = &spec.request_type {
            out.push_str(&format!("    request: {};\n", req));
        }
        if let Some(resp) = &spec.response_type {
            out.push_str(&format!("    response: {};\n", resp));
        } else {
            out.push_str("    response: unknown;\n");
        }

        out.push_str("  }\n");
    }

    out.push_str("}\n");
    out
}

fn route_meta_to_spec(meta: &RouteMeta) -> RouteTypeSpec {
    // Extract param names from the path (e.g. `/users/:id` → [("id", "string")]).
    let mut params = Vec::new();
    for seg in meta.path.split('/') {
        if let Some(name) = seg.strip_prefix(':') {
            params.push((name.to_string(), "string".to_string()));
        } else if let Some(name) = seg.strip_prefix('*') {
            params.push((name.to_string(), "string".to_string()));
        }
    }

    RouteTypeSpec {
        path: meta.path.clone(),
        method: meta.method,
        params,
        // V1: schemas are JSON Values, not typed. V2 will parse them into
        // proper TS types via a JSON-Schema → TypeScript converter.
        request_type: meta.request_schema.as_ref().map(|_| "unknown".to_string()),
        response_type: meta.response_schema.as_ref().map(|_| "unknown".to_string()),
    }
}

fn derive_interface_name(spec: &RouteTypeSpec) -> String {
    // /users/:id → GetUserById; /health → GetHealth; /echo/:name → PostEchoName
    let method = match spec.method {
        Method::Get => "Get",
        Method::Post => "Post",
        Method::Put => "Put",
        Method::Delete => "Delete",
        Method::Patch => "Patch",
        Method::Head => "Head",
        Method::Options => "Options",
    };
    let body: String = spec
        .path
        .split('/')
        .filter(|s| !s.is_empty())
        .map(|seg| {
            if let Some(name) = seg.strip_prefix(':') {
                // e.g. `:id` → `ById`
                let mut chars = name.chars();
                match chars.next() {
                    Some(c) => format!("By{}", c.to_uppercase().collect::<String>() + chars.as_str()),
                    None => String::new(),
                }
            } else if let Some(name) = seg.strip_prefix('*') {
                format!("Star{}", capitalise(name))
            } else {
                capitalise(seg)
            }
        })
        .collect::<Vec<_>>()
        .join("");
    format!("{}{}", method, body)
}

fn capitalise(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_basic_interface() {
        let routes = vec![RouteMeta {
            path: "/users/:id".into(),
            method: Method::Get,
            summary: None,
            tags: vec![],
            request_schema: None,
            response_schema: None,
        }];
        let ts = generate_typescript(&routes);
        assert!(ts.contains("interface GetUsersById"));
        assert!(ts.contains("path: '/users/:id'"));
        assert!(ts.contains("method: 'GET'"));
        assert!(ts.contains("id: string"));
    }

    #[test]
    fn derives_interface_names_for_each_method() {
        assert_eq!(
            derive_interface_name(&RouteTypeSpec {
                path: "/users".into(),
                method: Method::Get,
                params: vec![],
                request_type: None,
                response_type: None,
            }),
            "GetUsers"
        );
        assert_eq!(
            derive_interface_name(&RouteTypeSpec {
                path: "/echo/:name".into(),
                method: Method::Post,
                params: vec![("name".into(), "string".into())],
                request_type: None,
                response_type: None,
            }),
            "PostEchoByName"
        );
    }
}
