/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Compile a class string (e.g. "flex p-4 text-red-500") to CSS. */
export declare function compileCss(classes: string): string
/** Scan a directory for class= / className= usage and emit a minimal CSS bundle. */
export declare function compileCssDir(dir: string): string
/** Get the framework version. */
export declare function version(): string
/**
 * Start the Kungfu HTTP server on the given port. Returns a Promise that
 * resolves when the server stops.
 *
 * The server comes with built-in routes:
 *   - GET /hello → {"message":"world"}
 *   - GET /docs → Swagger UI
 *   - GET /openapi.json → OpenAPI 3.1 spec
 *
 * V1.1 will add JS handler registration via ThreadsafeFunction.
 */
export declare function startServer(port: number): Promise<void>
