//! `kungfu deploy` — generate Dockerfile + deployment configs.

use std::path::Path;

/// Generate a Dockerfile for the current project.
pub fn generate_dockerfile(project_name: &str, port: u16) -> String {
    format!(
        r#"# Auto-generated by `kungfu deploy`. Edit as needed.
FROM rust:1.96 AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --features "kungfu-core/io_uring kungfu-core/simd"

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/{name} /usr/local/bin/app
EXPOSE {port}
ENV RUST_LOG=info
CMD ["app"]
"#,
        name = project_name,
        port = port
    )
}

/// Generate a docker-compose.yml for the project.
pub fn generate_docker_compose(project_name: &str, port: u16) -> String {
    format!(
        r#"# Auto-generated by `kungfu deploy`. Edit as needed.
version: "3.9"
services:
  app:
    build: .
    ports:
      - "{port}:{port}"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
"#,
        port = port
    )
}

/// Generate a `.dockerignore`.
pub fn generate_dockerignore() -> &'static str {
    r#"target/
.git/
*.md
*.log
node_modules/
.env
"#
}

/// Generate a systemd service file.
pub fn generate_systemd_unit(project_name: &str, port: u16) -> String {
    format!(
        r#"[Unit]
Description={name} Kungfu App
After=network.target

[Service]
Type=simple
User=kungfu
WorkingDirectory=/opt/{name}
ExecStart=/opt/{name}/app
Restart=on-failure
RestartSec=5
Environment=RUST_LOG=info
Environment=PORT={port}

[Install]
WantedBy=multi-user.target
"#,
        name = project_name,
        port = port
    )
}

/// Write all deployment files to the project directory.
pub fn write_deploy_files(project_dir: &Path, project_name: &str, port: u16) -> std::io::Result<()> {
    std::fs::write(project_dir.join("Dockerfile"), generate_dockerfile(project_name, port))?;
    std::fs::write(project_dir.join("docker-compose.yml"), generate_docker_compose(project_name, port))?;
    std::fs::write(project_dir.join(".dockerignore"), generate_dockerignore())?;
    std::fs::write(
        project_dir.join(format!("{name}.service", name = project_name)),
        generate_systemd_unit(project_name, port),
    )?;
    Ok(())
}
